package com.meguri.core.react;

public enum ReactTerminationReason {
    MODEL_FINALIZED,
    MODEL_FAILED,
    WAITING_FOR_APPROVAL,
    DELEGATION_NOT_ENABLED,
    MODE_NOT_AGENT,
    MAX_ROUNDS,
    MAX_MODEL_CALLS,
    MAX_TOOL_CALLS,
    DEADLINE_EXCEEDED,
    TOKEN_BUDGET_EXHAUSTED,
    COST_BUDGET_EXHAUSTED,
    REPEATED_ACTION,
    REPEATED_FAILED_ACTION,
    NO_NEW_INFORMATION,
    EVIDENCE_SUFFICIENT,
    CONSECUTIVE_CAPABILITY_FAILURES,
    ACTION_REJECTED,
    CANCELLED,
    PLANNER_FAILED
}
